version: '3.2'

services:
  express-template:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: express-template-v1
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm run dev
volumes:
  node_modules: {}